services:
  app:
    depends_on:
      - db
    build: .
    entrypoint: ./docker-entrypoint.sh
    environment:
      - DB_DOMAIN=db

  db:
    image: postgres:16
    volumes:
      - postgres_data:/var/lib/postgres/data
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}

volumes:
  postgres_data:
